language: c++
dist: bionic
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y scons
  - sudo apt install libeigen3-dev

before_script:
  - git clone https://github.com/xanthospap/ggdatetime.git && cd ggdatetime
  - sudo scons install
  - cd ../
  - git clone https://github.com/xanthospap/matvec.git && cd matvec
  - sudo scons install
  - cd ../
  - git clone https://github.com/xanthospap/ggeodesy.git && cd ggeodesy
  - sudo scons install
  - cd ../
  - sudo ldconfig

script:
  - scons --use-eigen
  - scons debug=1 --use-eigen
